---
- name: Stop backend pod
  command: "kubectl scale deployment {{ backend_deployment }} --replicas=0"
  become: yes
  listen:
    - "restart web services"
- name: Apply deployment configuration
  command: "kubectl apply -f {{ home }}/backend.yml"
  become: yes
  listen:
    - "restart web services"

- name: Restart lighthttpd
  command: webservice --backend=kubernetes php7.2 restart
  become: yes
  listen:
    - "restart web services"
